// This test code is generated by ChatGPT
// Hence, I can't vouch for the implementation being production-ready.

package unit_test

import (
	"bytes"
	"fmt"
	"github.com/theghostmac/pluto/internal/core/blockchain"
	"github.com/theghostmac/pluto/internal/core/transactions"
	"github.com/theghostmac/pluto/internal/core/utils"
	"testing"
	"time"
)

func TestHeaderEncodeDecodeBinary(t *testing.T) {
	// Create a sample header with values.
	header := blockchain.Header{
		Version:           1,
		PreviousBlockHash: utils.RandomHash(),
		Timestamp:         time.Now().UnixNano(),
		Height:            10,
		Nonce:             67890,
	}

	// Encode the header to binary
	var encodedData bytes.Buffer
	if err := header.EncodeBinary(&encodedData); err != nil {
		t.Fatalf("Error encoding header: %v", err)
	}
	// Decode the encoded binary data back to header.
	decodedHeader := blockchain.Header{}
	if err := decodedHeader.DecodeBinary(&encodedData); err != nil {
		t.Fatalf("Error decoding header: %v", err)
	}

	// Complete original header with decoded header.
	if !headerEqual(header, decodedHeader) {
		t.Fatalf("Decoded header does not match the original header.")
	}

}

func headerEqual(h1, h2 blockchain.Header) bool {
	return h1.Version == h2.Version &&
		h1.PreviousBlockHash == h2.PreviousBlockHash &&
		h1.Timestamp == h2.Timestamp &&
		h1.Height == h2.Height &&
		h1.Nonce == h2.Nonce
}

func TestBlockEncodeDecodeBinary(t *testing.T) {
	// Create a sample block with header and transaction.
	block := blockchain.Block{
		Header: blockchain.Header{
			Version:           1,
			PreviousBlockHash: utils.Hash{},
			Timestamp:         time.Now().UnixNano(),
			Height:            15,
			Nonce:             67890,
		},
		Transactions: []transactions.Transactions{},
	}
	fmt.Print(block)
}
